language: node_js

env:
  - TARGET=test

node_js:
  - '6'
  - '7'
  - '8.10.0'
  - '10'

matrix:
  include:
    - name: Lint
      node_js: '8.10.0'
      env:
        - TARGET=lint
    - name: Coverage
      node_js: '8.10.0'
      env:
        - TARGET=coverage
    - name: Chrome headless
      node_js: '8.10.0'
      env:
        - TARGET=test-headless

script: npm run $TARGET

after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
